force-app/main/default/objects/Heuristic_Duplicate_Candidate__c/Heuristic_Duplicate_Candidate__c.object-meta.xml
<CustomObject>
  <label>Heuristic Duplicate Candidate</label>
  <nameField>
    <displayFormat>HDC-{000000}</displayFormat>
    <label>Candidate Number</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Heuristic Duplicate Candidates</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Heuristic_Duplicate_Candidate__c/fields/Scan__c.field-meta.xml
<CustomField>
  <fullName>Scan__c</fullName>
  <deleteConstraint>SetNull</deleteConstraint>
  <label>Scan</label>
  <referenceTo>Heuristic_Duplicate_Scan__c</referenceTo>
  <relationshipLabel>Heuristic Duplicate Candidates</relationshipLabel>
  <relationshipName>HeuristicDuplicateCandidates</relationshipName>
  <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HeuristicDuplicateCandidateCleanupBatch.cls
public with sharing class HeuristicDuplicateCandidateCleanupBatch implements Database.Batchable<SObject> {
  private Id scanId;

  public HeuristicDuplicateCandidateCleanupBatch(Id scanId) {
    this.scanId = scanId;
  }

  public Database.QueryLocator start(Database.BatchableContext bc) {
    return Database.getQueryLocator([
      SELECT Id
      FROM Heuristic_Duplicate_Candidate__c
      WHERE Scan__c = :scanId
    ]);
  }

  public void execute(Database.BatchableContext bc, List<SObject> scope) {
    Database.delete(scope, false);
  }

  public void finish(Database.BatchableContext bc) {
    if (!Test.isRunningTest()) {
      Database.executeBatch(new HeuristicDuplicatePairCleanupBatch(scanId), 2000);
    }
  }
}