force-app/main/default/objects/Heuristic_Duplicate_Pair__c/Heuristic_Duplicate_Pair__c.object-meta.xml
<CustomObject>
  <label>Heuristic Duplicate Pair</label>
  <nameField>
    <displayFormat>HDP-{000000}</displayFormat>
    <label>Pair Number</label>
    <type>AutoNumber</type>
  </nameField>
  <pluralLabel>Heuristic Duplicate Pairs</pluralLabel>
  <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Heuristic_Duplicate_Pair__c/fields/Scan__c.field-meta.xml
<CustomField>
  <fullName>Scan__c</fullName>
  <deleteConstraint>SetNull</deleteConstraint>
  <label>Scan</label>
  <referenceTo>Heuristic_Duplicate_Scan__c</referenceTo>
  <relationshipLabel>Heuristic Duplicate Pairs</relationshipLabel>
  <relationshipName>HeuristicDuplicatePairs</relationshipName>
  <type>Lookup</type>
</CustomField>

force-app/main/default/classes/HeuristicDuplicatePairCleanupBatch.cls
public with sharing class HeuristicDuplicatePairCleanupBatch implements Database.Batchable<SObject> {
  private Id scanId;

  public HeuristicDuplicatePairCleanupBatch(Id scanId) {
    this.scanId = scanId;
  }

  public Database.QueryLocator start(Database.BatchableContext bc) {
    return Database.getQueryLocator([
      SELECT Id
      FROM Heuristic_Duplicate_Pair__c
      WHERE Scan__c = :scanId
    ]);
  }

  public void execute(Database.BatchableContext bc, List<SObject> scope) {
    Database.delete(scope, false);
  }

  public void finish(Database.BatchableContext bc) {
  }
}